services:
  - type: web
    name: bale-bot-sums
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DEEPSEEK_KEY
        sync: false
